micronaut:
  application:
    name: mnIncremental
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    driverClassName: org.h2.Driver
    schema-generate: CREATE_DROP
    dialect: H2
jpa.default:
  entity-scan:
    packages: 'mn.incremental.groovy.domain'
  properties:
    hibernate.hbm2ddl.auto: update

netty:
  default:
    allocator:
      max-order: 3
